Updated plugin set for HP clusters

diff --git a/check_ECC-IPMI b/check_ECC-IPMI
--- a/check_ECC-IPMI
+++ b/check_ECC-IPMI
@@ -28,10 +28,11 @@
 # Pass the server IPMI interface IP address or name as the first parameter
 # N.B. This plugin should be run via sudo
 
-# Check alces IPMI monitor application is present and executable
-[[ -x /opt/gridware/alces/sbin/alces-ipmi ]] || exit 3
+# set ecc-check spool directory
+checkdir=/var/spool/nagios/ecc-check
 
-pid=$$
+# Check that ECC output files are available
+[[ -d $checkdir ]] || exit 3
 
 # Check that we've been passed a parameter
 remote=$1
@@ -40,13 +41,32 @@ if [ ! $remote ] ; then
    exit 3
 fi
 
-# the command to run to check the service
-checkcommand=`/opt/gridware/alces/sbin/alces-ipmi $remote -c 'sel list' 2> /dev/null | grep -i ECC | wc -l`
+# check we have output for this node
+if [ ! -f $checkdir/$remote.ecc.out ] ; then
+   echo "No log information found for $remote"
+   exit 3
+fi
 
-if [ `echo $checkcommand | awk '{print $1}'` -gt 0 ] ; then
-   echo "System event log for $remote has logged $checkcommand ECC memory event(s)"
+# the command to run to check the service
+checkcommand=`egrep -ic "ecc|memory" $checkdir/$remote.ecc.out | awk '{print $1}'`
+
+if [ $checkcommand -gt 0 ] ; then
+   # detected a memory fault, so check what type
+   uecc=`grep -ic " uncorrect" $checkdir/$remote.ecc.out | awk '{print $1}'`
+   cecc=`grep -ic " correctable" $checkdir/$remote.ecc.out | awk '{print $1}'`
+   if [ $uecc -gt 0 ] ; then
+      echo "Detected $uecc uncorrectable ECC errors on $remote"
+      exit 2
+   elif [ $cecc -gt 0 ] ; then
+      echo "Detected $cecc correctable ECC errors on $remote"
+      exit 1
+   else
+      echo "Detected $checkcommand memory errors on $remote"
+   fi
    exit 1
 else
+   # No faults found
    echo "No ECC events logged for $remote"
    exit 0
 fi
+
diff --git a/check_HPSA_P440 b/check_HPSA_P440
--- a/check_HPSA_P440
+++ b/check_HPSA_P440
@@ -24,34 +24,34 @@
 #                                                                              #
 ################################################################################
 
-# Script to check the status of the grid-engine master daemon via qping
+# Script to check the status of a HP hpacucli volume
+# Volume ID is passed as parameter 1
+# Adapter card is passed as parameter 2
+# N.B. This script needs to be run with SUDO by the nagios user
 
-# Set site variables (edit as necessary)
-# /opt/service/gridscheduler/2011.11p1_155/bin/linux-x64/qping
-geloc=/opt/service/gridscheduler/2011.11p1_155/
-qping=$geloc/bin/linux-x64/qping
+binary=/usr/sbin/hpssacli
+# Check monitor is present and executable
+if [ ! -x $binary ] ; then
+   echo "Cannot execute HP disk monitor - is it installed?"
+   exit 3
+fi
 
-# Check monitor application is present and executable
-[[ -x $qping ]] || exit 3
+vol=$1
+card=$2
 
-qmaster=`cat $geloc/etc/conf/act_qmaster`
-qmasterport=6444
+# Check that sg kernel module is loaded
+if [ `lsmod | egrep "^sg " | wc -l` -lt 1 ] ; then
+   modprobe sg > /etc/null 2>&1
+fi
 
-# Source grid engine settings
-#. /etc/profile.d/ge.sh
-. /etc/profile > /dev/null 2>&1
-module load services/gridscheduler
+# the command to run to check the service
+checkcommand=`$binary controller slot=$card logicaldrive $vol show | grep Status | head -1`
 
-# Run the monitor command grab the output and the exit status
-$qping -info $qmaster $qmasterport qmaster 1 > /var/tmp/qping.out 2> /dev/null
-exitcode=$?
-
-if [ $exitcode -eq 0 ] ; then
-   echo "Grid-engine status is okay - `grep clients /var/tmp/qping.out | awk '{print $5}'` connected clients"
-   rm -f /var/tmp/qping.out
-   exit 0
-else
-   echo "Detected grid-engine status warning - see /var/tmp/qping.out"
+if [ `echo $checkcommand | grep -c OK | awk '{print $1}'` -lt 1 ] ; then
+   echo "System disk RAID volume warning: `echo $checkcommand | sed 's?\t? ?g'`"
    exit 1
+else
+   echo "System disk RAID volume OK"
+   exit 0
 fi
 
diff --git a/check_ceph_osd b/check_ceph_osd
--- a/check_ceph_osd
+++ b/check_ceph_osd
@@ -24,34 +24,40 @@
 #                                                                              #
 ################################################################################
 
-# Script to check the status of the grid-engine master daemon via qping
+# Script to check the status of Ceph OSD daemons
+# Expected number of Ceph OSDs passed as first parameter
+# N.B. This script needs to be run with SUDO by the nagios user
 
-# Set site variables (edit as necessary)
-# /opt/service/gridscheduler/2011.11p1_155/bin/linux-x64/qping
-geloc=/opt/service/gridscheduler/2011.11p1_155/
-qping=$geloc/bin/linux-x64/qping
+# Check monitor is present and executable
+if [ ! -x /usr/bin/ceph ] ; then
+   echo "Cannot execute Ceph monitor - is it installed?"
+   exit 3
+fi
 
-# Check monitor application is present and executable
-[[ -x $qping ]] || exit 3
-
-qmaster=`cat $geloc/etc/conf/act_qmaster`
-qmasterport=6444
-
-# Source grid engine settings
-#. /etc/profile.d/ge.sh
-. /etc/profile > /dev/null 2>&1
-module load services/gridscheduler
-
-# Run the monitor command grab the output and the exit status
-$qping -info $qmaster $qmasterport qmaster 1 > /var/tmp/qping.out 2> /dev/null
-exitcode=$?
-
-if [ $exitcode -eq 0 ] ; then
-   echo "Grid-engine status is okay - `grep clients /var/tmp/qping.out | awk '{print $5}'` connected clients"
-   rm -f /var/tmp/qping.out
-   exit 0
-else
-   echo "Detected grid-engine status warning - see /var/tmp/qping.out"
+osds=$1
+if [ "$osds" == "" ] ; then
+   echo "Pass number of expected OSDs as first parameter"
    exit 1
+fi
+
+tmpfile=/var/tmp/cephcheck.$$
+
+# the command to run to check the service
+/usr/bin/ceph osd tree > $tmpfile
+
+foundosds=`grep osd $tmpfile | wc -l`
+uposds=`grep osd $tmpfile | grep -c up`
+rm -f $tmpfile
+
+if [ $foundosds -ne $osds ] ; then
+   echo "Found $foundosds OSD(s) active - expected $osds"
+   exit 1
+elif [ $uposds -ne $osds ] ; then
+   downosds=`expr $osds - $uposds`
+   echo "$downosds of $osds OSD(s) currently down"
+   exit 1
+else
+   echo "Found $uposds OSD(s) running"
+   exit 0
 fi
 
